CREATE TABLE IF NOT EXISTS todos(
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  status BOOLEAN,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
