run:
  timeout: 10m
  skip-dirs:
    - .docker
    - .github
    - proto

linters:
  enable-all: true
  disable:
    - maligned
    - dupl
    - wsl
    - godox
    - stylecheck
    - gci
    - godot
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - varnamelen
    - gochecknoglobals
    - golint
    - interfacer
    - scopelint
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam
    - wrapcheck
    - wastedassign
    - tagliatelle
    - paralleltest
    - gosec
  disable-all: false

linters-settings:
  funlen:
    lines: 270
    statements: 50
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 35

  gosimple:
    go: "1.18"

  misspell:
    locale: US

  staticcheck:
    go: "1.18"

  unused:
    go: "1.18"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - scopelint
        - funlen
        - gocognit
        - gosec
        - gochecknoinits
        - errcheck
  exclude-use-default: false
